spring:
  cache:
    cache-names: voyages
    caffeine:
      spec: maximumSize=100,expireAfterAccess=60s

  jackson:
    default-property-inclusion: non_empty
    serialization:
      write_dates_as_timestamps: false

security:
  basic:
    enabled: false
    realm: TrainTracker
