spring:
  cache:
    cache-names: voyages-hr,voyages-si
    caffeine:
      spec: maximumSize=100,expireAfterWrite=60s

  jackson:
    default-property-inclusion: non_empty
    serialization:
      write_dates_as_timestamps: false

  thymeleaf:
    mode: HTML

security:
  basic:
    enabled: false
    realm: TrainTracker
