name: "CI"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: chmod +x gradlew
      - run: ./gradlew check --stacktrace
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: chmod +x gradlew
      - env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: ./gradlew jib -Djib.to.image=registry.heroku.com/traintracker-io/web -Djib.to.auth.username=_ -Djib.to.auth.password=$(heroku auth:token)
      - env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku config:set SPRING_LIQUIBASE_ENABLED=true --app traintracker-io
      - env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web --app traintracker-io
      - env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku config:unset SPRING_LIQUIBASE_ENABLED --app traintracker-io
