name: "CI"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: chmod +x gradlew
      - run: ./gradlew check --stacktrace
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.repository == 'vpavic/traintracker' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          chmod +x gradlew
          ./gradlew jib -Djib.to.image=registry.heroku.com/traintrckr/web -Djib.to.auth.username=_ -Djib.to.auth.password=$(heroku auth:token)
          chmod +x deploy.sh
          ./deploy.sh
